port = 1323
process_name = "trailer_manager"
allow_origins = ["http://localhost:8080"]

[broker]
host = "127.0.0.1"
port = 1883
clientId = "trailer_manager"
topics = ["gps/log"]
username = "admin"
password = "admin"

[rdb]
driver = "postgres"
host = "127.0.0.1"
port = 5432
dbname = "trailer_manager"
username = "root"
password = "secret"

[cache]
driver = "redis"
host = "127.0.0.1"
port = 51496 #6379
db = 0
#password = secret
