// Code generated by sqlc. DO NOT EDIT.
// source: gps_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createGpsLog = `-- name: CreateGpsLog :one
INSERT INTO gps_log (
    sid,
    lat,
    lon,
    speed,
    wifi_loc,
    real_created_at
) VALUES (
	 $1, $2, $3, $4, $5, now()
 ) RETURNING sid, lat, lon, speed, wifi_loc, real_creaetd_at
`

type CreateGpsLogParams struct {
	Sid     string         `json:"sid"`
	Lat     string         `json:"lat"`
	Lon     string         `json:"lon"`
	Speed   sql.NullString `json:"speed"`
	WifiLoc []string       `json:"wifi_loc"`
}

func (q *Queries) CreateGpsLog(ctx context.Context, arg CreateGpsLogParams) (GpsLog, error) {
	row := q.db.QueryRowContext(ctx, createGpsLog,
		arg.Sid,
		arg.Lat,
		arg.Lon,
		arg.Speed,
		pq.Array(arg.WifiLoc),
	)
	var i GpsLog
	err := row.Scan(
		&i.Sid,
		&i.Lat,
		&i.Lon,
		&i.Speed,
		pq.Array(&i.WifiLoc),
		&i.RealCreaetdAt,
	)
	return i, err
}
