// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateGpsLog(ctx context.Context, arg CreateGpsLogParams) (GpsLog, error)
	CreateSensor(ctx context.Context, sid string) (Sensor, error)
	GetSensor(ctx context.Context, sid string) (Sensor, error)
	UpdateSensorLocation(ctx context.Context, arg UpdateSensorLocationParams) (Sensor, error)
}

var _ Querier = (*Queries)(nil)
